# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XBART_MH_cpp <- function(y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin = 1L, mtry = 0L, p_categorical = 0L, kap = 16, s = 4, verbose = FALSE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, nthread = 0, ctType = 1L, RepeatT = 5L, StepSize = 10L, MHB = TRUE, NWB = FALSE, FITB = TRUE) {
    .Call(`_XSBART_XBART_MH_cpp`, y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin, mtry, p_categorical, kap, s, verbose, parallel, set_random_seed, random_seed, sample_weights_flag, nthread, ctType, RepeatT, StepSize, MHB, NWB, FITB)
}

XBART_cpp <- function(y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin = 1L, mtry = 0L, p_categorical = 0L, kap = 16, s = 4, tau_kap = 3, tau_s = 0.5, verbose = FALSE, sampling_tau = TRUE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, nthread = 0, ctType = 1L, RepeatT = 5L, Sigmahat = 1.0, StepSize = 10L, MHB = TRUE, NWB = FALSE, FitB = TRUE) {
    .Call(`_XSBART_XBART_cpp`, y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin, mtry, p_categorical, kap, s, tau_kap, tau_s, verbose, sampling_tau, parallel, set_random_seed, random_seed, sample_weights_flag, nthread, ctType, RepeatT, Sigmahat, StepSize, MHB, NWB, FitB)
}

xbart_predict <- function(ctType, X, y_mean, tree_pnt) {
    .Call(`_XSBART_xbart_predict`, ctType, X, y_mean, tree_pnt)
}

r_to_json <- function(y_mean, tree_pnt) {
    .Call(`_XSBART_r_to_json`, y_mean, tree_pnt)
}

json_to_r <- function(json_string_r) {
    .Call(`_XSBART_json_to_r`, json_string_r)
}

r_to_json_3D <- function(tree_pnt) {
    .Call(`_XSBART_r_to_json_3D`, tree_pnt)
}

json_to_r_3D <- function(json_string_r) {
    .Call(`_XSBART_json_to_r_3D`, json_string_r)
}

sample_int_crank <- function(n, size, prob) {
    .Call(`_XSBART_sample_int_crank`, n, size, prob)
}

sample_int_ccrank <- function(n, size, prob) {
    .Call(`_XSBART_sample_int_ccrank`, n, size, prob)
}

sample_int_expj <- function(n, size, prob) {
    .Call(`_XSBART_sample_int_expj`, n, size, prob)
}

sample_int_expjs <- function(n, size, prob) {
    .Call(`_XSBART_sample_int_expjs`, n, size, prob)
}

